<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from wpriverthemes.com/HTML/drake/home1.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 26 Jul 2023 07:38:59 GMT -->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Naeem Maqbool - Web Developer</title>
    <link rel="icon" type="image/x-icon" href="assets/images/naeem.png">

    <!-- Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com/">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet">

    <!-- Stylesheet -->
    <link rel="stylesheet" href="assets/css/line-awesome/1.3.0/css/line-awesome.min.css">
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="assets/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="assets/css/animate.min.css">
    <link rel="stylesheet" href="assets/css/smooth-scrollbar.css">
    <link rel="stylesheet" href="assets/css/lightbox.min.css">

    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/responsive.css">

</head>
<body class="home1-page">

    <video class="body-overlay" muted autoplay loop>
        <source src="assets/images/video1.mp4" type="video/mp4">
    </video>

    <div class="page-loader">
        <div class="bounceball"></div>
    </div>

    <span class="icon-menu">
        <span class="bar"></span>
        <span class="bar"></span>
    </span>

    <div class="global-color">
        <span class="setting-toggle">
            <i class="las la-cog"></i>
        </span>
        <div class="inner">
            <div class="overlay"></div>
            <div class="global-color-option">
                <span class="close-settings">
                    <i class="las la-times"></i>
                </span>
                <h2>Configuration</h2>
                <div class="global-color-option-inner">
                    <p>Colors</p>
                    <div class="color-boxed">
                        <a href="#" class="clr-active" onclick="color1();"></a>
                        <a href="#" onclick="color2();"></a>
                        <a href="#" onclick="color3();"></a>
                        <a href="#" onclick="color4();"></a>
                        <a href="#" onclick="color5();"></a>
                        <a href="#" onclick="color6();"></a>
                        <a href="#" onclick="color7();"></a>
                        <a href="#" onclick="color8();"></a>
                    </div>

                    <!-- <p>THREE DIMENSIONAL SHAPES</p>
                    <ul class="themes">
                        <li class="active"><a href="home1.html">Earth Lines Sphere</a></li>
                        <li><a href="home2.html">3D Abstract Ball</a></li>
                        <li><a href="home3.html">Water Waves</a></li>
                        <li><a href="home4.html">Liquids Wavy</a></li>
                        <li><a href="home6.html">Solid Color</a></li>
                        <li><a href="home5.html">Simple Strings</a></li>
                    </ul> -->
                </div>
            </div>
        </div>
    </div>

    <div class="responsive-sidebar-menu">
        <div class="overlay"></div>
        <div class="sidebar-menu-inner">
            <div class="menu-wrap">
                <p>Menu</p>
                <ul class="menu scroll-nav-responsive d-flex">
                    <li>
                        <a class="scroll-to" href="#home">
                            <i class="las la-home"></i> <span>Home</span>
                        </a>
                    </li>
                    <li>
                        <a class="scroll-to" href="#about">
                            <i class="lar la-user"></i> <span>About</span>
                        </a>
                    </li>
                    <li>
                        <a class="scroll-to" href="#resume">
                            <i class="las la-briefcase"></i> <span>Resume</span>
                        </a>
                    </li>
                    <li>
                        <a class="scroll-to" href="#services">
                            <i class="las la-stream"></i> <span>Services</span>
                        </a>
                    </li>
                    <li>
                        <a class="scroll-to" href="#skills">
                            <i class="las la-shapes"></i> <span>Skills</span>
                        </a>
                    </li>
                    <li>
                        <a class="scroll-to" href="#portfolio">
                            <i class="las la-grip-vertical"></i> <span>Portfolios</span>
                        </a>
                    </li>
                    <li>
                        <a class="scroll-to" href="#testimonial">
                            <i class="lar la-comment"></i> <span>Testimonial</span>
                        </a>
                    </li>
                    <li>
                        <a class="scroll-to" href="#contact">
                            <i class="las la-envelope"></i> <span>Contact</span>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="sidebar-social">
                <p>Social</p>
                <ul class="social-links d-flex align-items-center">
                    <li>
                        <a href="#"><i class="lab la-twitter"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="lab la-dribbble"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="lab la-instagram"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <ul class="menu scroll-nav d-flex">
        <li>
            <a class="scroll-to" href="#home">
                <span>Home</span> <i class="las la-home"></i>
            </a>
        </li>
        <li>
            <a class="scroll-to" href="#about">
                <span>About</span> <i class="lar la-user"></i>
            </a>
        </li>
        <li>
            <a class="scroll-to" href="#resume">
                <span>Resume</span> <i class="las la-briefcase"></i>
            </a>
        </li>
        <li>
            <a href="#services">
                <span>Services</span> <i class="las la-stream"></i>
            </a>
        </li>
        <li>
            <a class="scroll-to" href="#skills">
                <span>Skills</span> <i class="las la-shapes"></i>
            </a>
        </li>
        <li>
            <a class="scroll-to" href="#portfolio">
                <span>Portfolios</span> <i class="las la-grip-vertical"></i>
            </a>
        </li>
        <li>
            <a class="scroll-to" href="#testimonial">
                <span>Testimonial</span> <i class="lar la-comment"></i>
            </a>
        </li>
        <li>
            <a class="scroll-to" href="#contact">
                <span>Contact</span> <i class="las la-envelope"></i>
            </a>
        </li>
    </ul>

    <div class="left-sidebar">
        <div class="sidebar-header d-flex align-items-center justify-content-between">
            <h2 style="color:white;font-size:22px;">Naeem Maqbool</h2>
            <span class="designation">Web Developer</span>
        </div>
        <img class="me" style="height:200px;" src="assets/images/naeem.png" alt="Me">
        <h2 class="email">naeemmaqbool08@gmail.com</h2>
        <h2 class="address">Lahore Pakistan</h2>
        <p class="copyright">&copy; 2023 Drake. All Rights Reserved</p>
        <ul class="social-profile d-flex align-items-center flex-wrap justify-content-center">
            <li>
                <a href="#"><i class="lab la-twitter"></i></a>
            </li>
            <li>
                <a href="#"><i class="lab la-dribbble"></i></a>
            </li>
            <li>
                <a href="#"><i class="lab la-instagram"></i></a>
            </li>
            <li>
                <a href="https://github.com/naeemmaqbool08" target="_blanks"><i class="lab la-github"></i></a>
            </li>
        </ul>
        <a href="https://wa.me/923498482236" target="_blank" class="theme-btn">
            <i class="las la-envelope"></i> Hire Me!
        </a>
    </div>

    <main class="drake-main">
        <div id="smooth-wrapper">
            <div id="smooth-content">

                <div class="left-sidebar">
                    <div class="sidebar-header d-flex align-items-center justify-content-between">
                        <h2 style="color:white;font-size:22px;">Naeem Maqbool</h2>
                        <span class="designation">Web Developer</span>
                    </div>
                    <img class="me" src="assets/images/naeem.png" alt="Me">
                    <h2 class="email">naeemmaqbool08@gmail.com</h2>
                    <h2 class="address">Lahore Pakistan</h2>
                    <p class="copyright">&copy; 2023 Drake. All Rights Reserved</p>
                    <ul class="social-profile d-flex align-items-center flex-wrap justify-content-center">
                        <li>
                            <a href="#"><i class="lab la-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="lab la-dribbble"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="lab la-instagram"></i></a>
                        </li>
                        <li>
                            <a href="https://github.com/naeemmaqbool08" target="_blanks"><i class="lab la-github"></i></a>
                        </li>
                    </ul>
                    <a href="https://wa.me/923498482236" target="_blank" class="theme-btn">
                        <i class="las la-envelope"></i> Hire Me!
                    </a>
                </div>

                <section class="hero-section page-section scroll-to-page" id="home">

                    <div class="custom-container">
                        <div class="hero-content content-width">
                            <div class="section-header">
                                <h4 class="subtitle scroll-animation" data-animation="fade_from_bottom">
                                    <i class="las la-home"></i> Introduce
                                </h4>
                                <h1 class="scroll-animation" data-animation="fade_from_bottom">PHP <span>Laravel</span>, React JS Expert</h1>
                            </div>
                            <p class="scroll-animation" data-animation="fade_from_bottom">Transforming ideas into interactive web realities. Creating online possibilities with code and creativity</p>
                            <a href="#portfolio" 
                                class="go-to-project-btn scroll-to scroll-animation" 
                                data-animation="rotate_up">
                                <img src="assets/images/round-text.png" alt="Rounded text">
                                <i class="las la-arrow-down"></i>
                            </a>
        
                            <div class="facts d-flex">
                                <div class="left scroll-animation" data-animation="fade_from_left">
                                    <h1>5+</h1>
                                    <p>Years of <br>Experience</p>
                                </div>
                                <div class="right scroll-animation" data-animation="fade_from_right">
                                    <h1>72+</h1>
                                    <p>projects completed on <br>15 countries</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
        
                <section class="about-area page-section scroll-to-page" id="about">
                    <div class="custom-container">
                        <div class="about-content content-width">
                            <div class="section-header">
                                <h4 class="subtitle scroll-animation" data-animation="fade_from_bottom">
                                    <i class="lar la-user"></i> About
                                </h4>
                                <h1 class="scroll-animation" data-animation="fade_from_bottom">
                                    A dedicated web developer <span></span></h1>
                            </div>
                            <p class="scroll-animation" data-animation="fade_from_bottom">
                                I specialize in Laravel and React development, 
                                weaving the power of backend and frontend technologies to create 
                                and dynamic web applications</p>
                        </div>
                    </div>
                </section>
        
        
                <section class="resume-area page-section scroll-to-page" id="resume">
                    <div class="custom-container">
                        <div class="resume-content content-width">
                            <div class="section-header">
                                <h4 class="subtitle scroll-animation" data-animation="fade_from_bottom">
                                    <i class="las la-briefcase"></i> Resume
                                </h4>
                                <h1 class="scroll-animation" data-animation="fade_from_bottom">Education & <span>Experience</span></h1>
                            </div>
        
                            <div class="resume-timeline">
                                <div class="item scroll-animation" data-animation="fade_from_right">
                                    <span class="date">2022 - Present</span>
                                    <h2>PHP Laravel Developer</h2>
                                    <p>Stars Developer</p>
                                    <h2>Mobile App Developer</h2>
                                    <p>Freelancer</p>
                                </div>
                                <div class="item scroll-animation" data-animation="fade_from_right">
                                    <span class="date">2021 - 2022</span>
                                    <h2>PHP Laravel Developer</h2>
                                    <p>Freelancer</p>
                                    <h2>Mobile App Developer</h2>
                                    <p>Freelance</p>
                                </div>
                                <div class="item scroll-animation" data-animation="fade_from_right">
                                    <span class="date">2017 - 2021</span>
                                    <h2>Bachelor Degree of Computer Science</h2>
                                    <p>GCU Faisalabad</p>
                                </div>
                            </div>
        
                        </div>
                    </div>
                </section>
        
        
                <section class="services-area page-section scroll-to-page" id="services">
                    <div class="custom-container">
                        <div class="services-content content-width">
                            <div class="section-header">
                                <h4 class="subtitle scroll-animation" data-animation="fade_from_bottom">
                                    <i class="las la-stream"></i> Services
                                </h4>
                                <h1 class="scroll-animation" data-animation="fade_from_bottom">My <span>Specializations</span></h1>
                            </div>
        
                            <div class="services-items">
                                <div class="service-item scroll-animation" data-animation="fade_from_bottom">
                                    <i class="las la-bezier-curve"></i>
                                    <h2>Backend Developer</h2>
                                    <p>I build website go live with PHP, Laravel or JS</p>
                                    <span class="projects">70 Projects</span>
                                </div>
                                <div class="service-item scroll-animation" data-animation="fade_from_bottom">
                                    <i class="las la-code"></i>
                                    <h2>Frontend Developer</h2>
                                    <p>I created digital products with unique ideas use React & Node JS</p>
                                    <span class="projects">70 Projects</span>
                                </div>
                                <div class="service-item scroll-animation" data-animation="fade_from_bottom">
                                    <i class="las la-bezier-curve"></i>
                                    <h2>Mobile App Developer</h2>
                                    <p>Turning ideas into intuitive mobile experiences</p>
                                    <span class="projects">8 Projects</span>
                                </div>
                            </div>
        
                        </div>
                    </div>
                </section>
        
        
                <section class="skills-area page-section scroll-to-page" id="skills">
                    <div class="custom-container">
                        <div class="skills-content content-width">
                            <div class="section-header">
                                <h4 class="subtitle scroll-animation" data-animation="fade_from_bottom">
                                    <i class="las la-shapes"></i> my skills
                                </h4>
                                <h1 class="scroll-animation" data-animation="fade_from_bottom">My <span>Advantages</span></h1>
                            </div>
        
                            <div class="row skills text-center">
                                <div class="col-md-3 scroll-animation" data-animation="fade_from_bottom">
                                    <div class="skill">
                                        <div class="skill-inner">
                                            <img src="assets/images/laravel.png" alt="Laravel/PHP">
                                            <h1 class="percent">97%</h1>
                                        </div>
                                        <p class="name">Laravel/PHP</p>
                                    </div>
                                </div>
                                <div class="col-md-3 scroll-animation" data-animation="fade_from_right">
                                    <div class="skill">
                                        <div class="skill-inner">
                                            <img src="assets/images/react.png" alt="React">
                                            <h1 class="percent">90%</h1>
                                        </div>
                                        <p class="name">React</p>
                                    </div>
                                </div>
                                <div class="col-md-3 scroll-animation" data-animation="fade_from_right">
                                    <div class="skill">
                                        <div class="skill-inner">
                                            <img style="height: 62px;" src="assets/images/nodejs.png" alt="React">
                                            <h1 class="percent">70%</h1>
                                        </div>
                                        <p class="name">Node JS</p>
                                    </div>
                                </div>
                            </div>
        
                        </div>
                    </div>
                </section>
        
        
                <section class="portfolio-area page-section scroll-to-page" id="portfolio">
                    <div class="custom-container">
                        <div class="portfolio-content content-width">
                            <div class="section-header">
                                <h4 class="subtitle scroll-animation" data-animation="fade_from_bottom">
                                    <i class="las la-grip-vertical"></i> portfolio
                                </h4>
                                <h1 class="scroll-animation" data-animation="fade_from_bottom">Featured <span>Projects</span></h1>
                            </div>
        
                            <div class="row portfolio-items">
                                <div class="col-md-12 scroll-animation" data-animation="fade_from_bottom">
                                    <div class="portfolio-item portfolio-half">
                                        <div class="portfolio-item-inner">
                                            <a href="assets/images/ecom.png" data-lightbox="example-1">
                                                <img src="assets/images/ecom.png" alt="Portfolio">
                                            </a>
        
                                            <ul class="portfolio-categories">
                                                <li>
                                                    <a href="#">Laravel</a>
                                                </li>
                                            </ul>
                                        </div>
                                        <h2><a href="https://knestsolutions.com/" target="_blank">Knest - Ecommerce Store (Canada)</a></h2>
                                    </div>
                                </div>

                                <div class="col-md-12 scroll-animation" data-animation="fade_from_bottom">
                                    <div class="portfolio-item portfolio-full">
                                        <div class="portfolio-item-inner">
                                            <a href="assets/images/sporteuropa.png" data-lightbox="example-1">
                                                <img src="assets/images/sporteuropa.png" alt="Portfolio">
                                            </a>
        
                                            <ul class="portfolio-categories">
                                                <li>
                                                    <a href="#">PHP</a>
                                                </li>
                                                <li>
                                                    <a href="#">Laravel</a>
                                                </li>
                                                <li>
                                                    <a href="#">Javascript</a>
                                                </li>
                                            </ul>
                                        </div>
                                        <h2><a href="https://sporteuropa-online.com/" target="_blank">Sporteuropa - Sports Website (Italy)</a></h2>
                                    </div>
                                </div>
        
                                <div class="col-md-6 scroll-animation" data-animation="fade_from_left">
                                    <div class="portfolio-item portfolio-half">
                                        <div class="portfolio-item-inner">
                                            <a href="assets/images/deeptime.png" data-lightbox="example-1">
                                                <img src="assets/images/deeptime.png" alt="Portfolio">
                                            </a>

                                            <img src="assets/images/portfolio2.jpg"  alt="Portfolio">
        
                                            <ul class="portfolio-categories">
                                                <li>
                                                    <a href="#">PHP Laravel</a>
                                                </li>
                                                <li>
                                                    <a href="#">React</a>
                                                </li>
                                            </ul>
                                        </div>
                                        <h2><a href="https://deeptime-digital.com/" target="_blank">Deeptime - Time Tracker (USA)</a></h2>
                                    </div>
                                </div>
        
                                <div class="col-md-6 scroll-animation" data-animation="fade_from_right">
                                    <div class="portfolio-item portfolio-half">
                                        <div class="portfolio-item-inner">
                                            <a href="assets/images/steponedollar.png" data-lightbox="example-1">
                                                <img src="assets/images/steponedollar.png" alt="Portfolio">
                                            </a>
        
                                            <ul class="portfolio-categories">
                                                <li>
                                                    <a href="#">PHP</a>
                                                </li>
                                                <li>
                                                    <a href="#">Laravel</a>
                                                </li>
                                            </ul>
                                        </div>
                                        <h2><a href="http://steponedollar.pears.info/" target="_blank">StepOneDollar - Investment (Pakistan)</a></h2>
                                    </div>
                                </div>
        
                                <div class="col-md-12 scroll-animation" data-animation="fade_from_bottom">
                                    <div class="portfolio-item portfolio-half">
                                        <div class="portfolio-item-inner">
                                            <a href="assets/images/easyprocure.png" data-lightbox="example-1">
                                                <img src="assets/images/easyprocure.png" alt="Portfolio">
                                            </a>
        
                                            <ul class="portfolio-categories">
                                                <li>
                                                    <a href="#">Laravel</a>
                                                </li>
                                                <li>
                                                    <a href="#">Blade</a>
                                                </li>
                                            </ul>
                                        </div>
                                        <h2><a href="https://easyprocure.pears.info/" target="_blank">EasyProcure - 2DV Dashboard (UK)</a></h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
        
        
                <section class="testimonial-area page-section scroll-to-page" id="testimonial">
                    <div class="custom-container">
                        <div class="testimonial-content content-width">
                            <div class="section-header">
                                <h4 class="subtitle scroll-animation" data-animation="fade_from_bottom">
                                    <i class="lar la-comment"></i> testimonial
                                </h4>
                                <h1 class="scroll-animation" data-animation="fade_from_bottom">Trusted by <span>Hundered Clients</span></h1>
                            </div>
        
                            <div class="testimonial-slider-wrap scroll-animation" data-animation="fade_from_bottom">
                                <div class="owl-carousel testimonial-slider owl-theme">
                                    <div class="testimonial-item">
                                        <div class="testimonial-item-inner">
                                            <div class="author d-flex align-items-center">
                                                <img src="assets/images/anonymous.jpg" alt="Testimonial">
                                                <div class="right">
                                                    <h3>Luca Lana Tim</h3>
                                                    <p class="designation">CEO of Sporteuropa <span>Italy</span></p>
                                                </div>
                                            </div>
                                            <p>“Naeem works fast, fully understanding job needs and finding solutions
                                                that make the result more stable and reliable. Communication is quick 
                                                and easy and is always available. This is the second work he produces and I
                                                am fully satisfied with it.
                                                He deserves to work ”</p>
        
                                            <a href="https://sporteuropa-online.com/" target="_blank" class="project-btn">Sporteuropa</a>
                                        </div>
                                    </div>
                                    <div class="testimonial-item">
                                        <div class="testimonial-item-inner">
                                            <div class="author d-flex align-items-center">
                                                <img src="assets/images/anonymous.jpg" alt="Testimonial">
                                                <div class="right">
                                                    <h3>Shawna</h3>
                                                    <p class="designation">Work Flow Management <span>USA</span></p>
                                                </div>
                                            </div>
                                            <p>“Naeem and his team did an amazing job coding my web application.
                                                They made sure they understood what I wanted and communicated clearly
                                                throughout the entire process. I highly recommend Naeem and look forward
                                                to working with him on future projects.”</p>
        
                                            <a href="https://broker-smarter.com/" target="_blank" class="project-btn">Work Flow Management</a>
                                        </div>
                                    </div>
                                    <div class="testimonial-item">
                                        <div class="testimonial-item-inner">
                                            <div class="author d-flex align-items-center">
                                                <img src="assets/images/anonymous.jpg" alt="Testimonial">
                                                <div class="right">
                                                    <h3>Johnny Maghzal</h3>
                                                    <p class="designation">Employee Tracking Tool <span>USA</span></p>
                                                </div>
                                            </div>
                                            <p>“Naeem is great! He helped us a lot and he was very patient with us.
                                                We had set the specs of project well and he completed all the tasks successfully.
                                                We will be hiring him again in the next couple of months to add some
                                                enhancement to the project he built for us after we do some market testing.
                                                Thank you Naeem”</p>
        
                                            <a href="https://deeptime-digital.com/" target="_blank" class="project-btn">Deeptime Digital</a>
                                        </div>
                                    </div>
                                    <div class="testimonial-item">
                                        <div class="testimonial-item-inner">
                                            <div class="author d-flex align-items-center">
                                                <img src="assets/images/anonymous.jpg" alt="Testimonial">
                                                <div class="right">
                                                    <h3>Victor Lami</h3>
                                                    <p class="designation">One Click Access <span>USA</span></p>
                                                </div>
                                            </div>
                                            <p>“Good team, works hard; Quality of work is good. Will do his best to satisfy
                                                his customers. Hi English is understandable and good in chat communications.
                                                Wish him luck”</p>
        
                                            <a href="https://oneclickaccess.pears.info/" target="_blank" class="project-btn">Desktop App</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="testimonial-footer-nav">
                                    <div class="testimonial-nav d-flex align-items-center">
                                        <button class="prev"><i class="las la-angle-left"></i></button>
                                        <div id="testimonial-slide-count"></div>
                                        <button class="next"><i class="las la-angle-right"></i></button>
                                    </div>
                                </div>
                            </div>
        
                            <div class="clients-logos">
                                <h4 class="scroll-animation" data-animation="fade_from_bottom">work with 60+ brands worldwide</h4>
                                <div class="row align-items-center">
                                    <div class="col-md-3 scroll-animation" data-animation="fade_from_left">
                                        <img src="assets/images/sporteuropa.jpeg" alt="Client">
                                    </div>
                                    <div class="col-md-3 scroll-animation" data-animation="fade_from_bottom">
                                        <img style="height: 80px;" src="assets/images/deepico.png" alt="Client">
                                    </div>
                                    <div class="col-md-3 scroll-animation" data-animation="fade_from_top">
                                        <img style="height: 80px;" src="assets/images/oneclikcaccess.png" alt="Client">
                                    </div>
                                    <div class="col-md-3 scroll-animation" data-animation="fade_from_right">
                                        <img style="height: 80px;" src="assets/images/knest.png" alt="Client">
                                    </div>
                                </div>
                            </div>
        
                        </div>
                    </div>
                </section>


                <section class="contact-area page-section scroll-content" id="contact">
                    <div class="custom-container">
                        <div class="contact-content content-width">
                            <div class="section-header">
                                <h4 class="subtitle scroll-animation" data-animation="fade_from_bottom">
                                    <i class="las la-dollar-sign"></i> contact
                                </h4>
                                <h1 class="scroll-animation" data-animation="fade_from_bottom">Let's Work <span>Together!</span></h1>
                            </div>
                            <h3 class="scroll-animation" data-animation="fade_from_bottom">naeemmaqbool08@gmail.com</h3>
                            <p id="required-msg">* Marked fields are required to fill.</p>

                            <form class="contact-form scroll-animation" data-animation="fade_from_bottom" method="POST" action="contact.php">
                                <div class="alert alert-success messenger-box-contact__msg" style="display: none" role="alert">
                                    Your message was sent successfully.
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="input-group">
                                            <label for="full-name">full Name <sup>*</sup></label>
                                            <input type="text" name="full-name" id="full-name" placeholder="Your Full Name">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="input-group">
                                            <label for="email">Email <sup>*</sup></label>
                                            <input type="email" name="email" id="email" placeholder="Your email adress">
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="input-group">
                                            <label for="phone-number">phone <span>(optional)</span></label>
                                            <input type="text" name="phone-number" id="phone-number" placeholder="Your number phone">
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="input-group">
                                            <label for="message">message</label>
                                            <textarea name="message" id="message" placeholder="Wrire your message here ..."></textarea>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="input-group submit-btn-wrap">
                                            <button class="theme-btn" name="submit" type="submit" id="submit-form">send message</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </main>
    

    <script src="assets/js/jquery.js"></script>
    <script src="assets/js/bootstrap.bundle.min.js"></script>
    <script src="assets/js/owl.carousel.js"></script>
    <script src="assets/js/gsap.min.js"></script>
    <script src="assets/js/ScrollTrigger.min.js"></script>
    <script src="assets/js/ScrollToPlugin.min.js"></script>
    <script src="assets/js/lightbox.min.js"></script>
    
    <script src="assets/js/main.js"></script>
    <script src="assets/js/ajax-form.js"></script>
    <script src="assets/js/color.js"></script>
</body>

<!-- Mirrored from wpriverthemes.com/HTML/drake/home1.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 26 Jul 2023 07:39:00 GMT -->
</html>